services:
  db:
    image: postgres:16-bullseye
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d chatbot_db -U chatbot_admin" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    env_file: "./.env"
    volumes:
      - db_data:/var/lib/postgresql/data
  chromadb:
    image: chromadb/chroma:latest
    command: --host 0.0.0.0 --port 8200
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # default path, change it as needed
      - ANONYMIZED_TELEMETRY=False
    ports:
      - 8200:8200
    healthcheck:
      test: [ "CMD", "/bin/bash", "-c", "cat < /dev/null > /dev/tcp/localhost/8200" ]
      interval: 10s
      timeout: 5s
      retries: 3
  api:
    working_dir: /home/backend
    build: .
    command: bash -c "uvicorn api.server:server --reload --host 0.0.0.0 --port 3100"
    ports:
      - "3100:3100"
    env_file: "./.env"
    depends_on:
      db:
        condition: service_healthy
        restart: true
      chromadb:
        condition: service_healthy
        restart: true
    volumes:
      - ./api:/home/backend/api
volumes:
  db_data:
  chroma_data:
    driver: local
